#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["GrubHubClone.Order/GrubHubClone.Order.csproj", "GrubHubClone.Order/"]
COPY ["GrubHubClone.Common.Dtos/GrubHubClone.Common.Dtos.csproj", "GrubHubClone.Common.Dtos/"]
COPY ["GrubHubClone.Common.Models/GrubHubClone.Common.Models.csproj", "GrubHubClone.Common.Models/"]
COPY ["GrubHubClone.Common.Exceptions/GrubHubClone.Common.Exceptions.csproj", "GrubHubClone.Common.Exceptions/"]
COPY ["GrubHubClone.Common/GrubHubClone.Common.csproj", "GrubHubClone.Common/"]
RUN dotnet restore "GrubHubClone.Order/GrubHubClone.Order.csproj"
COPY . .
WORKDIR "/src/GrubHubClone.Order"
RUN dotnet build "GrubHubClone.Order.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GrubHubClone.Order.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY ["GrubHubClone.Order/appsettings.Development.json", "Config/appsettings.Production.json"]
RUN rm -rf appsettings.json
RUN rm -rf appsettings.Development.json
ENTRYPOINT ["dotnet", "GrubHubClone.Order.dll"]