name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  DOTNET_VERSION: "7.0.x"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore ./GrubHubClone.sln

    - name: Build
      run: dotnet build ./GrubHubClone.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./GrubHubClone.sln --configuration Release --no-restore

